[tool.poetry]
name = "airlift"
version = "0.1.0"
description = "Upload & Merge Data with Attachments to Airtable"
authors = ["Arjun <arjunprakash027@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
airlift = "airlift.cli:main"

[tool.poetry.dependencies]
python = "^3.8"
pyairtable = "^2.1.0.post1"
requests = "^2.31.0"
tqdm = "^4.66.1"
pydrive = "^1.3.1"
dropbox = "^11.36.2"

[tool.poetry.group.dev.dependencies]
pyairtable = "^2.1.0.post1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
