name: airtable_delete_database_entries_test

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *' # Runs at 8 AM Singapore time (00:00 UTC) daily
      
env:
  BUILD_PYTHON_VERSION: "3.14"
  BUILD_POETRY_VERSION: "2.4.1"
  BUILD_SETUPTOOLS_VERSION: "82.0.1"
  BUILD_POETRY_PLUGIN_EXPORT_VERSION: "1.10.0"
  PACKAGE_NAME: airlift

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Install setuptools
        run: pip install setuptools==${{ env.BUILD_SETUPTOOLS_VERSION }}

      - name: Set up Poetry ${{ env.BUILD_POETRY_VERSION }}
        uses: abatilo/actions-poetry@v3.0.2
        with:
          poetry-version: ${{ env.BUILD_POETRY_VERSION }}
          poetry-plugins: poetry-plugin-export==${{ env.BUILD_POETRY_PLUGIN_EXPORT_VERSION }}

      - name: Cache Poetry dependencies
        uses: actions/cache@v5
        with: 
          path: |
            .venv
            ~/.cache/pypoetry
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-
              
      - name: Install the necessary libraries to run airlift
        run: poetry install --no-root

      - name: Run delete database entries test
        env:
          CI_AIRTABLE_TOKEN: ${{secrets.CI_AIRTABLE_TOKEN}}
          CI_AIRTABLE_BASE: ${{secrets.CI_AIRTABLE_BASE}}
          CI_AIRTABLE_TABLE: ${{secrets.CI_AIRTABLE_TABLE}}
          CI_DROPBOX_APP_KEY: ${{secrets.CI_DROPBOX_APP_KEY}}
          CI_DROPBOX_REFRESH_TOKEN: ${{secrets.CI_DROPBOX_REFRESH_TOKEN}}
          
        run: pytest tests/test_delete_database_entries.py -v -s --disable-warnings

      - name: Run empty Dropbox folder test
        env:
          CI_DROPBOX_APP_KEY: ${{secrets.CI_DROPBOX_APP_KEY}}
          CI_DROPBOX_REFRESH_TOKEN: ${{secrets.CI_DROPBOX_REFRESH_TOKEN}}
          
        run: pytest tests/test_empty_dropbox_folder.py -v -s --disable-warnings

